default_pulling_interval: 100
token:  U7hBxf6aJIz8Vv4ptatm5C7uGQHoEhuWCJGsbQHb
platform_host_url: http://localhost:8080
profilers:
  - type: postgres
    name: my_postgres
    host: localhost
    port: 5432
    username: postgres
    password: ""
    database: fake_pii
