default_pulling_interval: 100
token:
platform_host_url: http://localhost:8080
profilers:
  - type: <adapter_type>
    name: <adapter_name>
    host: <host>
    port: <port>
    username: <username>
    password: <password>
    database: <database>