default_pulling_interval: 100
token: <token>
platform_host_url: http://localhost:8080
profilers:
  - type: <type>
    name: <name>
    host: <host>
    username: <username>
    password: <password>
    port: <port>
    database: <database>